"""empty message

Revision ID: 050a00f01443
Revises: 
Create Date: 2025-05-29 07:51:43.038419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050a00f01443'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('options',
    sa.Column('options_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=1), nullable=False),
    sa.Column('text', sa.String(length=225), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('options_id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.Integer(), nullable=False),
    sa.Column('answers_id', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.answer_id'], ),
    sa.ForeignKeyConstraint(['pat_id'], ['pat.id'], ),
    sa.ForeignKeyConstraint(['question_no'], ['questions.question_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('options')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('pat')
    # ### end Alembic commands ###
